---
development:
  username: USERNAME
  password: PASSWORD
  url: https://demochurch.ccbchurch.com/api.php
test:
  username: USERNAME
  password: PASSWORD
  url: https://demochurch.ccbchurch.com/api.php
production:
  username: USERNAME
  password: PASSWORD
  url: https://demochurch.ccbchurch.com/api.php
